### ISSUE TITLE
Usage unclear (from dotnet/cli#3239)

### ISSUE THREAD

**Issue by liamdawson** [liamdawson/DotNet.DevFeed#4]
From https://github.com/dotnet/cli/issues/3239#issuecomment-278765223

> @liamdawson read about usage, but it's not really clear how does one take advantage of that. Could you please explain how to use such tool in a typical tool development cycle on local dev machine:
> 
> > tool edit -> tool build -> tool pack -> ??? -> client restore -> client build -> dotnet tool client\project\dir
>
> Thanks!

**Comment by liamdawson** [comment]
This application handles the first four steps, and optionally steps 5 & 6 via support for running a command after each pack.

Essentially, it hosts a custom nuget feed that you can support via adding a [nuget config file and setting the package sources to the local feed this runs](https://docs.microsoft.com/en-us/nuget/schema/nuget-config-file#package-source-sections). If you ran the command via `dotnet dev-feed . --port 5001`, the feed location would be `http://localhost:5001/` if I recall correctly.

Sorry, I haven't had reason to work on this for a while, but any contributions to documentation (or code!) are welcome.

**Comment by BrainCrumbz** [comment]
Let's see if we have a clear picture:

## One-time setup

### In tool package project

1. Add `"tools": { "Dawsonsoft.DotNet.DevFeed.Tools": { "version": "1.0.0-beta1-*", "imports": "portable-net45+win8+dnxcore50" } },` to `project.json`
1. `dotnet restore`
1. `dotnet dev-feed . --port 5001`

### In client project

1. Edit `nuget.config` to add a package source pointing to `http://localhost:5001/`
1. `dotnet restore`

## Development cycle

### In tool package project 

1. Edit code
1. `dotnet build` (necessarily from a new shell, not from the one where *dev-feed* is still running)
1. At this point, local dev feed is up-to-date with the modified version

### In client project

1. `dotnet restore`
1. At this point, client project gets installed the modified version of package, **with no need to uninstall it first** and **with no need to step up version number in package project**

Does this make sense? And is it the way it is supposed to work?

Thanks!

**Comment by liamdawson** [comment]
Provided your version number in your project.json for the tool project ends with a `*`, and I believe that process is correct.

**Comment by BrainCrumbz** [comment]
Why?

**Comment by liamdawson** [comment]
This tool takes advantage of `dotnet-pack` [version suffix support](https://docs.microsoft.com/cs-cz/dotnet/articles/core/tools/dotnet-pack), which replaces the `-*` with the given suffix (which it automatically sets to the next available version number).
